# Generated by Django 2.2.2 on 2019-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='host_email',
            field=models.CharField(default='juni@gmail.com', max_length=200),
        ),
    ]
