# Generated by Django 2.2.2 on 2019-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='host_id',
            field=models.IntegerField(default=0),
        ),
    ]
