# Generated by Django 2.2.2 on 2019-07-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contacts.Contact'),
        ),
    ]
