# Generated by Django 2.2.2 on 2019-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190728_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='host_photo',
            field=models.ImageField(default='glasses.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing_photo',
            field=models.ImageField(default='asd.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
