# Generated by Django 2.2.2 on 2019-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20190729_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='host_photo',
            field=models.ImageField(blank='glasses.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='listing_photo',
            field=models.ImageField(blank='asd.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_photo',
            field=models.ImageField(blank='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
