# Generated by Django 2.2.2 on 2019-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20190730_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='host_name',
            field=models.CharField(default='juni', max_length=200),
        ),
    ]
