# Generated by Django 2.2.2 on 2019-08-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20190801_1637'),
        ('contacts', '0010_contact_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
    ]
