# Generated by Django 2.2.2 on 2019-08-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20190801_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='listing',
            field=models.CharField(max_length=200),
        ),
    ]
