# Generated by Django 2.2.2 on 2019-08-01 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190801_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contact',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
