# Generated by Django 2.2.2 on 2019-08-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_remove_inbox_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='start_time',
        ),
    ]
