# Generated by Django 2.2.2 on 2019-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20190801_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='listing',
            field=models.CharField(default='Junaid', max_length=200),
        ),
    ]
