# Generated by Django 2.2.2 on 2019-06-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190630_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='host',
            new_name='host_id',
        ),
    ]
