# Generated by Django 2.2.2 on 2019-07-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20190630_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
