# Generated by Django 2.2.2 on 2019-07-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20190701_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='host_id',
            new_name='host',
        ),
    ]
