# Generated by Django 2.2.2 on 2019-07-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
