# Generated by Django 2.2.2 on 2019-07-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='attendies',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='wifi',
            field=models.BooleanField(default=True),
        ),
    ]
