# Generated by Django 2.2.2 on 2019-07-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20190707_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Rules',
            new_name='rules',
        ),
    ]
