# Generated by Django 2.2.4 on 2019-09-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20190801_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
    ]
