# Generated by Django 2.2.4 on 2019-09-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_remove_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
