# Generated by Django 2.2.2 on 2019-06-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default=12345, max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='password2',
            field=models.CharField(default=12345, max_length=50),
        ),
    ]
