# Generated by Django 2.2.2 on 2019-06-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20190625_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='password',
        ),
        migrations.RemoveField(
            model_name='host',
            name='password2',
        ),
    ]
