# Generated by Django 2.2.2 on 2019-06-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20190625_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='host',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
