# Generated by Django 2.2.2 on 2019-07-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20190627_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='email',
        ),
    ]
